exports.ranks = [
    'inspector general',
    'deputy inspector-general of police',
    'assistant inspector-general of police',
    'commisioner of Police',
    'deputy commisioner of police',
    'assistant commisioner of police',
    'chief superintendent of police',
    'superintendent of police',
    'deputy superintendent of police',
    'assistant superintendent of police',
    'inspector of police',
    'sergeant major',
    'sergeant',
    'corporal',
    'lance',
    'constable',
]

exports.states = [
    'abia',
    'adamawa',
    'akwa Ibom',
    'anambra',
    'bauchi',
    'bayelsa',
    'benue',
    'borno',
    'cross River',
    'delta',
    'ebonyi',
    'edo',
    'ekiti',
    'enugu',
    'gombe',
    'imo',
    'jigawa',
    'kaduna',
    'kano',
    'katsina',
    'kebbi',
    'kogi',
    'kwara',
    'lagos',
    'nasarawa',
    'niger',
    'ogun',
    'ondo',
    'osun',
    'oyo',
    'plateau',
    'rivers',
    'sokoto',
    'taraba',
    'yobe',
    'zamfara',
    'abuja'
]